# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cb8669cd4b65f47a3ad2ceaca9e661c2c97564413665a639c1ff34b8f7c1921bcc97cf90895040e275e1724f7fc4ac544e1e2a3e43c24481ceb43bb42781d0a6

test:
  secret_key_base: 45a2deb397ae7d62da4606a84a02085759ecda792fae3daca0bba45fb822d54e7fdbbf63e2adb2c6b584f0862c5914924b09441a1d1e74a34b84c5809df36e03

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
